### ISSUE TITLE
请问这个算作弊吗？应该只是模拟鼠标操作吧？

### ISSUE THREAD

**Issue by BaldStrong** [perhaps-yo/zhihuishu#4]
请问这个算作弊吗？应该只是模拟鼠标操作吧？

**Comment by pacumlaft** [comment]
同问，就差两天就截止了，自己还有论文的deadline要赶，实在没空刷，但又怕这个会被算作弊。求问您用这个有被判定为不良吗？

**Comment by Pull256** [comment]
目前感觉ok，似乎没有被封号

**Comment by LiuZhaohui666** [comment]
> 同问，就差两天就截止了，自己还有论文的deadline要赶，实在没空刷，但又怕这个会被算作弊。求问您用这个有被判定为不良吗？
上面的老哥，感觉怎么样？用完有问题吗
